[package]
name = "trent"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.54", features = ["derive"] }
memmap2 = "0.9.9"
quinn = "0.11.9"
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_yaml = "0.9.34"
tempfile = "3.24.0"
tokio = { version = "1", features = ["full"] }
zstd = "0.13.3"
rusqlite = { version = "0.32", features = ["bundled"] }
serde_json = "1"
time = { version = "0.3", features = ["serde", "formatting"] }
